server:
  port: 9000

spring:
  main:
    web-application-type: reactive
  application:
    name: devquest-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
    gateway:
      routes:
        - id: user-service
          uri: lb://devquest-user-service
          predicates:
            - Path=/api/auth/**,/api/users/**
        - id: question-service
          uri: lb://devquest-question-service
          predicates:
            - Path=/api/questions/**,/api/answers/**,/api/comments/**,/api/votes/**,/api/favorites/**,/api/tags/**,/api/drafts/**
        - id: ai-service
          uri: lb://devquest-ai-service
          predicates:
            - Path=/api/ai/**
        - id: search-service
          uri: lb://devquest-search-service
          predicates:
            - Path=/api/search/**
        - id: notification-service
          uri: lb://devquest-notification-service
          predicates:
            - Path=/api/notifications/**
        - id: admin-service
          uri: lb://devquest-admin-service
          predicates:
            - Path=/api/admin/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456

sa-token:
  token-name: Authorization
  timeout: 86400
  is-concurrent: true
  is-share: true
  token-style: uuid
